from selenium.webdriver.common.by import By

class Pagelocator:
    user_name = (By.XPATH, "//input[@name='username']")
    pass_field = (By.XPATH, "//input[@name='password']")
    log_btn = (By.XPATH, "//button[@type='submit']")
    admin_item = (By.XPATH, "//span[text()='Admin']")
    pim_item = (By.XPATH, "//span[text()='PIM']")
    leave_item= (By.XPATH, "//span[text()='Leave']")
    time_item = (By.XPATH, "//span[text()='Time']")
    recruitment_item = (By.XPATH, "//span[text()='Recruitment']")
    myinfo_item = (By.XPATH, "//span[text()='My Info']")
    performance_item = (By.XPATH, "//span[text()='Performance']")
    dashboard_item = (By.XPATH, "//span[text()='Dashboard']")
    logout_dropdown = (By.XPATH, "//p[@class='oxd-userdropdown-name']")
    logout_btn = (By.XPATH, "//a[text()='Logout']")
    add_user = (By.XPATH, "//button[normalize-space()='Add']")
    user_role = (By.XPATH, "(//div[@class='oxd-select-text-input'])[1]")
    ess_user = (By.XPATH, "//div[@role='listbox']//span[text()='ESS']")
    emp_name = (By.XPATH, "//input[@placeholder='Type for hints...']")
    employee_hint = (By.XPATH, "(//div[@role='listbox']//span)[1]")
    status_field = (By.XPATH, "//label[text()='Status']/following::div[contains(@class,'oxd-select-text-input')][1]")
    enable_field = (By.XPATH,"//div[@role='listbox']//span[text()='Enabled']")
    emp_user = (By.XPATH, "//label[text()='Username']/following::input[1]")
    emp_pass = (By.XPATH, "(//input[@type='password'])[1]")
    emp_conf_pass = (By.XPATH, "(//input[@type='password'])[2]")
    save_btn = (By.XPATH, "//button[@type='submit']")
    user_status_user = (By.XPATH, "(//div[@class='oxd-select-text-input'])[2]")
    user_search_btn = (By.XPATH, "//button[text()=' Search ']")
    forgot_pass =(By.XPATH,"//p[text()='Forgot your password? ']")
    forgot_user = (By.XPATH, "//input[@placeholder='Username']")
    reset_password = (By.XPATH, "//button[text()=' Reset Password ']")
    reset_pass_msg = (By.XPATH, "//h6[text()='Reset Password link sent successfully']")
    user_personal = (By.XPATH, "//a[text()='Personal Details']")
    user_personal_field = (By.XPATH, "//h6[text()='Personal Details']")
    user_contact = (By.XPATH, "//a[text()='Contact Details']")
    user_contact_field = (By.XPATH, "//h6[text()='Contact Details']")
    user_emergency = (By.XPATH, "//a[text()='Emergency Contacts']")
    user_emergency_field = (By.XPATH, "//h6[text()='Assigned Emergency Contacts']")
    user_dependant = (By.XPATH, "//a[text()='Dependents']")
    user_dependant_field =(By.XPATH, "//h6[text()='Assigned Dependents']")
    user_immigration = (By.XPATH, "//a[text()='Immigration']")
    user_immigration_field = (By.XPATH, "//h6[text()='Assigned Immigration Records']")
    user_job = (By.XPATH, "//a[text()='Job']")
    user_job_field = (By.XPATH, "//h6[text()='Job Details']")
    user_salary = (By.XPATH, "//a[text()='Salary']")
    user_salary_field = (By.XPATH, "//h6[text()='Assigned Salary Components']")
    user_report = (By.XPATH, "//a[text()='Report-to']")
    user_report_field = (By.XPATH, "//h6[text()='Report to']")
    user_qualification = (By.XPATH, "//a[text()='Qualifications']")
    user_qualification_field = (By.XPATH, "//h6[text()='Qualifications']")
    user_membership = (By.XPATH, "//a[text()='Memberships']")
    user_membership_field = (By.XPATH, "//h6[text()='Assigned Memberships']")
    assign_leave_btn = (By.XPATH, "//a[text()='Assign Leave']")
    leave_employee_name = (By.XPATH, "//input[@placeholder='Type for hints...']")
    leave_emp_drop = (By.XPATH, "(//div[@role='listbox']//span)[1]")
    leave_type = (By.XPATH, "//div[text()='-- Select --']")
    leave_type_drop = (By.XPATH, "(//div[@role='listbox']//span)[4]")
    leave_from_date = (By.XPATH, "//label[text()='From Date']/following::input[@placeholder='yyyy-mm-dd'][1]")
    leave_to_date = (By.XPATH, "//label[text()='To Date']/following::input[@placeholder='yyyy-mm-dd'][1]")
    leave_days = (By.XPATH, "//label[text()='Partial Days']/following::div[text()='-- Select --']")
    leave_days_drop = (By.XPATH, "(//div[@role='listbox']//span)[1]")
    leave_days_duration = (By.XPATH,"//label[text()='Duration']/following::div[text()='-- Select --']")
    leave_duration_drop = (By.XPATH, "(//div[@role='listbox']//span)[1]")
    leave_comments = (By.XPATH, "//label[text()='Comments']/following::textarea[1]")
    leave_assign_btn = (By.XPATH, "//button[text()=' Assign ']")
    leave_confirm_popup = (By.XPATH, "//div[contains(@class,'oxd-dialog-container')]")
    leave_ok_btn = (By.XPATH, "//div[contains(@class,'oxd-dialog-container')]//button[normalize-space()='Ok']")
    leave_message = (By.XPATH, "//p[contains(@class,'oxd-toast-content')]")
    emp_claim = (By.XPATH, "//span[text()='Claim']")
    emp_claim_btn = (By.XPATH, "//button[text()=' Submit Claim ']")
    emp_claim_event = (By.XPATH, "(//div[text()='-- Select --'])[1]")
    emp_claim_currency = (By.XPATH, "//label[text()='Currency']/following::div[contains(@class,'oxd-select-text-input')]")
    emp_claim_event_drop = (By.XPATH, "(//div[@role='listbox']//span)[1]")
    emp_claim_currency_drop = (By.XPATH, "(//div[@role='listbox']//span)[4]")
    emp_claim_remarks = (By.XPATH, "//label[text()='Remarks']/following::textarea[1]")
    emp_claim_create_btn = (By.XPATH, "//button[text()=' Create ']")
    emp_claim_sub_btn = (By.XPATH, "//button[text()=' Submit ']")
    emp_claim_myclaim = (By.XPATH, "//a[text()='My Claims']")
    success_toast = (
        By.XPATH,
        "//div[contains(@class,'oxd-toast')]//p[contains(.,'Successfully Saved')]"
    )



